### PR TITLE
Linking Docs 

### PR DESCRIPTION
**Pull request by bu7maydAbdu**
more links on  6 files 
done it  late but better late than never i guess  haha

### CODE REVIEW

**Comment by clabe45** [comment]
Thank you for making this PR! Don't worry about being late haha. 

It looks good, but there's no need for the **content/** and **.md** parts, though. Are you starting the development server with `npm start` and opening localhost:1111 in your browser? Can you please do that and check the links you added?

**Comment by bu7maydAbdu** [comment]
i always get this error when i try npm start 


 >etro-site@1.0.0 start
> zola serve

'zola' is not recognized as an internal or external command,
operable program or batch file.




also downloaded zola binary from  their github but it doesn't run

**Comment by clabe45** [comment]
Oh, and you ran `npm install` first?

What was the error from the downloaded binary?

**Comment by bu7maydAbdu** [comment]
when i cloned it the first time i did  npm install and it gave me this error

> etro-site@1.0.0 prepublish
> npm run build


> etro-site@1.0.0 build
> rm -r public; zola build && cp CNAME public && cd etro && npm i && npm run doc && mv docs ../public/docs/api && git restore package-lock.json

rm: cannot remove 'public;': No such file or directory
rm: cannot remove 'zola': No such file or directory
rm: cannot remove 'build': No such file or directory
npm ERR! code 1
npm ERR! path C:\Users\yasee\OneDrive\Desktop\Codes\etro-js.github.io
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c npm run build

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\yasee\AppData\Local\npm-cache\_logs\2022-06-25T20_16_31_483Z-debug.log




the binary  didn't  run at all lol  ,  when I run it, it opens a CLI and  closes it immediately

**Pull request closed without merging**
