### PR TITLE
changed the link in overview.md line 28 from See the [ documentation](…

### PR DESCRIPTION
**Pull request by bu7maydAbdu**
…../api/classes/movie.html) to See the [ documentation](./movies.md). 

any suggestions or edits  i should make ?

### CODE REVIEW

**Comment by bu7maydAbdu** [comment]
this is a demo PR    to confirm that this way  is the right way of fixing, what do u think ?

**Comment by clabe45** [comment]
Thanks again for contributing! Looks good.

I'm going to rebase and update the commit message (I like to keep the first line a brief summary, followed by a blank line, followed by an optional longer description).

**Comment by clabe45** [comment]
It looks like next time I need to press merge from the web UI instead of the command line for it register haha

**Comment by bu7maydAbdu** [comment]
haha great then  , i will  re commit and change the commit message , also will add other edits

**Comment by clabe45** [comment]
No need, I reworded the commit and that went through, but the PR just didn't close. Should be all set now

**Pull request closed without merging**
